### PR TITLE
Fully support Symfony 4 and 5

### PR DESCRIPTION
**Pull request by Olaf1989**
- Set PHP 7.1 as minimum
- Added PHP typehinting
- Set Symfony 4 and 5 as required
- Added [EasyCodingStandard](https://github.com/Symplify/EasyCodingStandard)
- Updated README.md

### CODE REVIEW

**Comment by Gregwar** [comment]
Hello,

Can you explain what standard you are using to reformat the whold code?

For example, as specified in PSR-12, binaries operator should be surrounded by spaces, and your commit removes the spaces around the concatenation operator:
https://www.php-fig.org/psr/psr-12/#62-binary-operators

Thank for your work

**Comment by Gregwar** [comment]
Ok, just realized Symfony coding standard are not respecting PSR-12, since it it saying otherwise here:
https://symfony.com/doc/current/contributing/code/standards.html#structure

**Comment by Olaf1989** [comment]
> 
> 
> @Olaf1989 looks for me this table is not correct as it seems 2.1 which does support symfony 4 and 5?

You are right, I expected to go up a major version. I see that you have already created a pull request.

**Comment by Gregwar** [comment]
I accepted the PR to fix the table, however I am open to any suggestion if you think it makes mor sense to tag `v3.0.0` for e.g.

**Pull request merged**
