### PR TITLE
Support of multiple instance

### PR DESCRIPTION
**Pull request by cengizhancaliskan**

### CODE REVIEW

**Comment by cengizhancaliskan** [comment]
@Gregwar

**Comment by core23** [comment]
@Gregwar is this project still alive?

**Comment by Gregwar** [comment]
Yes, but I am not really reactive those time, sorry for that
Do not hesitate to bump me like you did yo trigger my attention
I'll try to do a review session next week

**Comment by broiniac** [comment]
@Gregwar Sorry, I don't want to be rude, but this pull request will close ~3 open issues.
It's almost 18 months old right now. Furthermore I believe, that I'm not the only one, who spent couple hours to crack this one on my own.

**Comment by Gregwar** [comment]
Thanks for contributing and sorry for the delay

**Comment by Gregwar** [comment]
I tagged `v2.0.6` so you can have a new major version for deps

**Pull request merged**
