### PR TITLE
Add Symfony 7 in required version for Symfony

### PR DESCRIPTION
**Pull request by macintoshplus**
Not fully tested on Symfony 7.0. But Kernel boot successfully.

### CODE REVIEW

**Comment by michnovka** [comment]
I did some testing, did not find any issues. Can we have this merged please?

**Comment by YoannChabert** [comment]
Some news to merge it ?

**Comment by michnovka** [comment]
See https://github.com/Gregwar/CaptchaBundle/pull/240 , it is a more comprehensive fix

**Comment by macintoshplus** [comment]
Thanks @michnovka. I close this PR.

**Pull request closed without merging**
