### PR TITLE
Remove Symfony 5 deprecations and add PHPstan

### LINKED ISSUE #217: Symfony 5.1: "Psr\Container\ContainerInterface" autowiring alias is deprecated
Hi there, in Symfony 5.1 the profiler shows this message under "deprecations":

> Since symfony/dependency-injection 5.1: The "Psr\Container\ContainerInterface" autowiring alias is deprecated. Define it explicitly in your app if you want to keep using it. It is being referenced by the "gregwar_captcha.controller" service.

### PR DESCRIPTION
**Pull request by Olaf1989**
Fixes #217

### CODE REVIEW

**Comment by Olaf1989** [comment]
@Gregwar do you have time to check this?

**Comment by malutanpetronel** [comment]
> @Gregwar

seems good to go :)

**Comment by Gregwar** [comment]
Sorry for the (huge) delay
Thanks for contributing

**Comment by Gregwar** [comment]
Tagged `v2.1.6`

**Pull request merged**
