### PR TITLE
Make it more unique

### PR DESCRIPTION
**Pull request by max-kovpak**
If you have 2 forms on one page time will be not unique

### CODE REVIEW

**Comment by Gregwar** [comment]
Why `rand(0,9)`?
I think this will require PHP to get a random number anyway, so why not just rand()?

**Comment by max-kovpak** [comment]
it's only for example. Just make it more unique.

**Comment by Gregwar** [comment]
ok
can you replace rand(0,9) with mt_rand()?

**Comment by max-kovpak** [comment]
Done

**Comment by Gregwar** [comment]
Thanks for contributing

**Pull request merged**
