### PR TITLE
add sf 4.0 support

### PR DESCRIPTION
**Pull request by andreybolonin**

### CODE REVIEW

**Comment by iltar** [comment]
When adding 4.0 support, don't forget to make the services public, as they will fail in 4.0 due to being private. Example:

```
PHP Deprecated: The "gregwar_captcha.generator" service is private, getting it from the
container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make 
the service public, or stop using the container directly and use dependency injection 
instead.
```

**Comment by Gregwar** [comment]
@iltar is adding the `public` keyword a bc break?

**Comment by andreybolonin** [comment]
@iltar @Gregwar ``public: true`` done

**Comment by Gregwar** [comment]
Ok
Thanks

**Pull request merged**
