### PR TITLE
Use getBlockPrefix() instead of getName() for SF 3.0

### PR DESCRIPTION
**Pull request by StudioMaX**

### CODE REVIEW

**Comment by Herod** [comment]
+1

**Comment by StudioMaX** [comment]
Ping @Gregwar

**Comment by Restless-ET** [comment]
:+1:  on this. I was about to make a similar PR myself. :)

**Comment by StudioMaX** [comment]
Fixed by https://github.com/Gregwar/CaptchaBundle/pull/163

**Pull request closed without merging**
